// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"H2A_GameKit/check","status":true,"description":"最新の JS 構文に対応しているかテスト","parameters":{}},
{"name":"H2A_GameKit/main","status":true,"description":"ゲームキット基本機能","parameters":{}},
{"name":"--------------------","status":false,"description":"--------------------------------------------------","parameters":{}},
{"name":"factory/PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"factory/ButtonPicture","status":true,"description":"ピクチャをクリック可能にします。","parameters":{}},
{"name":"factory/TextPicture","status":true,"description":"テキストをピクチャとして表示します。","parameters":{}},
{"name":"factory/CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"AlwaysDash":"false","CommandRemember":"false","TouchUi":"true","BgmVolume":"100","BgsVolume":"100","MeVolume":"100","SeVolume":"100","EraseAlwaysDash":"false","EraseCommandRemember":"false","EraseTouchUi":"false","EraseBgmVolume":"false","EraseBgsVolume":"false","EraseMeVolume":"false","EraseSeVolume":"false"}},
{"name":"factory/H2A_TileOptimizedScreen","status":true,"description":"タイルサイズに合わせて画面サイズを最適化","parameters":{}},
{"name":"--------------------","status":false,"description":"--------------------------------------------------","parameters":{}}
];
